app/models.py
from flask_login import UserMixin
from . import db, login_manager



# database schema/representation on ORM

class User(db.Model, UserMixin):
	__tablename__ = 'users'

	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(40))
	password = db.Column(db.String(40))
	cookie = db.Column(db.String(100))
	phone_no = db.Column(db.Integer())
	admin = db.Column(db.Boolean)
	manager = db.Column(db.Boolean)
	check_in = db.Column(db.String(15))


	@login_manager.user_loader
	def load_user(user_id):
		return User.query.get(int(user_id))

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

import redis
from flask_kvsession import KVSessionExtension
from simplekv.memory.redisstore import RedisStore


st = RedisStore(redis.StrictRedis())

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'

from config import config


def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)

	bootstrap.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)

	KVSessionExtension(st, app)

	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)

	return app

app/main/__init__.py
from ..models import User

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from datetime import datetime, date, timedelta
from flask import render_template, flash, url_for, request, redirect, session
from flask_login import login_user, current_user, logout_user
from .form import LoginForm, RegistrationForm, CheckInForm
from ..models import User, db
from ..decorators import is_admin, is_manager
from . import main
from .. import st



# checking for attendance

@main.route('/attendance', methods=['GET'])
@is_manager
def attendance():
	users = User.query.all()
	a = []
	for user in users:
		name = user.username
		key = user.cookie
		try:
			value = st.get(key)
		except:
			value = 'Not checked in yet'
			check_in = '----'
		if value != 'Not checked in yet':
			value = 'checked In, Working'
			check_in = user.check_in
		phone_no = user.phone_no

		b = [name, value, check_in[:-10], phone_no ]
		a.append(b)
	return render_template('attendance.html', users=a)



# index page

@main.route('/', methods=['GET'])
def index():
	return render_template('index.html')



# logging admin/manager in

@main.route('/login', methods=['GET', 'POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username=form.username.data).first()
		if user and user.password == form.password.data and user.manager:
			login_user(user)
			cookie_val = request.cookies.get('session').split(".")[0] 
			try:
				st.get(user.cookie)
			except:
				user.check_in = str(datetime.now().time())
			user.cookie = cookie_val
			db.session.add(user)
			db.session.commit()
			return redirect(url_for('.office'))
		return render_template('index.html')
	return render_template('login.html', form=form)



# only manager and admin can access (links for attendance & user creation)

@main.route('/office', methods=['GET', 'POST'])
@is_manager
def office():
	return render_template('office.html', admin=current_user.admin)



# creating a new user (only admin can access)

@main.route('/new_user', methods=['GET', 'POST'])
@is_admin
def new_user():
	form = RegistrationForm()
	if form.validate_on_submit():
		user = User(username=form.username.data, password=form.password.data, phone_no=form.phone_no.data, admin=form.admin.data, manager=form.manager.data)
		db.session.add(user)
		db.session.commit()
		flash('New user has been created')
		return redirect(url_for('.office'))
	return render_template('register.html', form=form)



# checking a user in

@main.route('/check-in', methods=['GET', 'POST'])
def check_in():
	form = CheckInForm()
	if form.validate_on_submit():
		user = User.query.filter_by(phone_no=form.phone_no.data).first()
		# cookie_val = request.cookies.get('session').split(".")[0]
		if not user or user.admin or user.manager:
			flash('Contact the Admin')
			return redirect(url_for('.index'))
		try:
			st.get(user.cookie)
			flash('Already logged In')
			return redirect(url_for('.index'))
		except:
			login_user(user)
			cookie_val = request.cookies.get('session').split(".")[0]
			user.cookie = cookie_val
			user.check_in = str(datetime.now().time())
			db.session.add(user)
			db.session.commit()
			flash('You are checked In, Now.')
			return redirect(url_for('.index'))

		flash('Invalid Username or Password')
	return render_template('login.html', form=form)



# logging the user out (admin/manager)

@main.route('/logout', methods=['GET', 'POST'])
def logout():
	logout_user()
	flash('You have been logged out')
	return redirect(url_for('.index'))



# custom error handler for 403 

@main.errorhandler(403)
def page_not_found(e):
    return render_template('403.html'), 403

app/templates/attendance.html
{% extends 'base.html'%}

{% block styles %}
{{super()}}
<link rel="stylesheet"
      href="{{url_for('static', filename='mystyle.css')}}">
{% endblock %}

{% block page_content %}


<div class="container table-container"> 

<h3>Table for availability</h3>
<hr>

<table style="width:100%; padding-top:30%; margin-top: 40px;", class="table-striped">
        <tr>
          <th>Name</th>
          <th>Availability</th>
          <th>Check In Time</th>
          <th>Phone</th>
        </tr>
      {% for user in users %}
        <tr>
          <td>{{ user[0] }}</td>
          <td>{{ user[1] }}</td> 
          
          <td>{{ user[2] }}</td>
          <td>{{ user[3] }}</td>
        </tr>
      {% endfor %}
</table>

</div>
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet"
      href="{{url_for('static', filename='mystyle.css')}}">
{% endblock %}

{% block title %} Flask {% endblock %}

{% block navbar %}

{% endblock %}


{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}

    {% endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

{% block page_content %}





	<div class="align">
		<a href="{{ url_for('main.check_in') }}">
			<button type="button" class="btn btn-info btn-lg btn-block">Check In</button>
		</a>
		
		<a href="{{ url_for('main.login') }}">
			<button type="button" class="btn btn-warning btn-lg btn-block">Manager</button>
		</a>
		
		<a href="{{ url_for('main.login') }}">
			<button type="button" class="btn btn-danger btn-lg btn-block">Admin</button>
		</a>
	</div>






{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}


{% block page_content %}
<div class="page-header">
	<h1>Check In</h1>
</div>
<div class="col-md-4">
	{{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/office.html
{% extends 'base.html'%}

{% block page_content %}


<div class="align">
	{% if admin %}
		<a href="{{ url_for('main.new_user') }}">
			<button type="button" class="btn btn-info btn-lg btn-block">New User</button>
		</a>
	{% endif %}
		<a href="{{ url_for('main.attendance') }}">
			<button type="button" class="btn btn-info btn-lg btn-block">Attendance</button>
		</a>
	</div>

	<a href="{{ url_for('main.logout') }}"><button class="btn btn-info">Logout</button></a>



{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}


{% block page_content %}
<div class="page-header">
	<h1>Register</h1>
</div>
<div class="col-md-4">
	{{ wtf.quick_form(form) }}
</div>

{% endblock %}